integrate yapper

diff --git a/scripts/runit b/scripts/runit
--- a/scripts/runit
+++ b/scripts/runit
@@ -82,6 +82,7 @@ set +a;
 
 just build_release --features="until"
 
+pids=()
 for (( i=0; i<$nodes; i++ )); do
     sig_priv_key="TIMEBOOST_DEMO_SIGNATURE_PRIVATE_KEY_$i"
     dec_priv_key="TIMEBOOST_DEMO_DECRYPTION_PRIVATE_KEY_$i"
@@ -93,7 +94,6 @@ for (( i=0; i<$nodes; i++ )); do
         --until $rounds
         --nodes $nodes
         --keyset-file $keyset_file
-        --tps $tps
         --stamp "${stamp}-$i.sf"
         --watchdog-timeout $rounds)
 
@@ -109,7 +109,33 @@ for (( i=0; i<$nodes; i++ )); do
     TIMEBOOST_SIGNATURE_PRIVATE_KEY=${!sig_priv_key} \
     TIMEBOOST_DECRYPTION_PRIVATE_KEY=${!dec_priv_key} \
     "${cmd[@]}" &
+    pids+=($!)
 done
 
-wait
+if [ -n "$tps" ] && [ "$tps" -gt 0 ]; then
+    cmd="RUST_LOG=yapper=info \
+    ./target/release/yapper \
+        --tps $tps \
+        --nodes $nodes \
+        --keyset-file $keyset_file"
+    eval "$cmd" &
+    pid=$!
+    echo "Started yapper with PID $pid at $tps TPS"
+fi
+
+for pid in "${pids[@]}"; do
+    wait $pid
+    exit_code=$?
+
+    if [ $exit_code -eq 0 ]; then
+        echo "Process $pid completed successfully with exit code $exit_code."
+    else
+        echo "Process $pid failed with exit code $exit_code."
+    fi
+done
+
+if [ -n "$tps" ] && [ "$tps" -gt 0 ]; then
+    echo "Attempting to kill yapper..."
+    pkill -f yapper
+fi
 
